title: Ent-Lab Group
logo: /assets/img/new-logo.png
description: Embedded and Networked Things Group, University of Trento, Italy
show_downloads: false
google_analytics:
#theme: jekyll-theme-minimal
theme: minima

sidebar:
  - name: Home
    icon: <span class="material-symbols-outlined"> home </span>
    link: https://tinysystems.github.io/
  - name: About
    icon: <span class="material-symbols-outlined"> settings_accessibility </span>
    link: /about.html
  - name: Members
    icon: <span class="material-symbols-outlined"> groups </span>
    link: /members.html
  - name: Open Source Projects
    icon: <span class="material-symbols-outlined"> view_timeline </span>
    link: /open-source.html   
  - name: Publications
    icon: <span class="material-symbols-outlined"> star_half </span>
    link: https://scholar.google.com.tr/citations?hl=en&user=LXUvnL0AAAAJ&view_op=list_works&sortby=pubdate 
  - name: Collaborations
    icon: <span class="material-symbols-outlined"> diversity_3 </span>
    link: /collab.html
  - name: Contact
    icon: <span class="material-symbols-outlined"> contact_phone </span>
    link: /contact.html

publications:
  - name: "AdaMICA: Adaptive Multicore Intermittent Computing"
    link: 
    venue: "Proc. ACM Interact. Mob. Wearable Ubiquitous Technol. Volume 6, Issue 4, September 2022 and ACM UbiComp 2022"    
  - name: "Immortal Threads: Multithreaded Event-driven Intermittent Computing on Ultra-Low-Power Microcontrollers"
    link: https://www.usenix.org/conference/osdi22/presentation/yildiz
    venue: "16th USENIX Symposium on Operating Systems Design and Implementation (OSDI 22)"
  - name: "Virtualizing Intermittent Computing"
    link: https://ieeexplore.ieee.org/document/9778211
    venue: "IEEE Internet of Things Journal 2022"
  - name: "NORM: An FPGA-based Non-volatile Memory Emulation Framework for Intermittent Computing"
    link: https://dl.acm.org/doi/abs/10.1145/3517812
    venue: ACM Journal on Emerging Technologies in Computing Systems (JETC) 2022
